site_name: OZ-Compass
site_author: javalive@winesoft.co.kr
site_url: http://winesoft.co.kr

theme: readthedocs

markdown_extensions:
    - admonition

nav:
    - Overview: index.md
    - Usecases:
        - Image Server : usecases/image.md
        - API Server: usecases/api.md
    - User Guide:
        - Web API: userguide/webapi.md
        - Configuration: userguide/config.md
        - Mapper: userguide/mapper.md
        - View: userguide/view.md
        - Operations: userguide/operations.md
    - About:
        - Release Notes: about/releasenotes.md
        - License: about/license.md

copyright: Copyright 2020 WINESOFT All Rights Reserved.
google_analytics: ['UA-70981026-11', 'winesoft.co.kr']

plugins:
    - search